FROM golang:1.21-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./
COPY .env ./

RUN go run main.go

FROM alpine

WORKDIR /app

COPY --from=build /app/main ./

CMD ["/app/main"]